@startuml TemplateUC

'/ !include C:/path/to/file.puml
'/ !includeurl link to file

left to right direction
'skinparam dpi 300
skinparam monochrome true
skinparam backgroundColor transparent
skinparam packageStyle rectangle
skinparam defaultTextAlignment center

' variables
!unquoted function actor( $name, $var )
    actor :$name: as $var
!endfunction

!unquoted function uc( $name, $var )
    usecase ($name) as $var
!endfunction

' relations
!unquoted function association( $first, $second, $line = "-", $swap = "false" )
    !if ( checkCharactersExceptSimpleLine($line) == "true" )
        !assert %false() : "The only recognized character is: -"
    !endif
    !if ( (%not( $swap == "true" )) && (%not( $swap == "false" )) )
        !assert %false() : "Invalid swap argument"
    !endif

    !if ($swap =="false")
        $first $line $second
    !endif
    !if ($swap =="true")
        $second $line $first
    !endif
!endfunction

!unquoted function generalization( $father, $child, $line = "-", $swap = "false", $whosTheFather = 1 )
    !if ( checkCharactersExceptSimpleLine($line) == "true" )
        !assert %false() : "The only recognized characters is: -"
    !endif
    !if ( (%not( $whosTheFather == 1 )) && (%not( $whosTheFather == 2 )) )
        !assert %false() : "Invalid father selection argument"
    !endif
    !if ( (%not( $swap == "true")) && (%not( $swap == "false" )) )
        !assert %false() : "Invalid swap argument"
    !endif

    !if ( $whosTheFather == 1 )
        !if ( $swap == "false" )
            $father <|$line $child
        !endif
        !if ( $swap == "true" )
            $child $line|> $father
        !endif
    !endif
    !if ( $whosTheFather == 2 )
        !if ( $swap == "false" )
            $father $line|> $child
        !endif
        !if ( $swap == "true" )
            $child <|$line $father
        !endif
    !endif
!endfunction

!unquoted function include( $first, $second, $line = ".", $swap = "false", $whoStarts = 1, $needSpace = "false" )
    !if ( checkCharactersExceptDot($line) == "true" )
        !assert %false() : "The only recognized characters is: ."
    !endif
    !if ( (%not( $whoStarts == 1 )) && (%not( $whoStarts == 2 )) )
        !assert %false() : "Invalid include argument"
    !endif
    !if ( (%not( $swap == "true")) && (%not( $swap == "false" )) )
        !assert %false() : "Invalid swap argument"
    !endif
    !if ( (%not( $needSpace == "true")) && (%not( $needSpace == "false" )) )
        !assert %false() : "Invalid space argument"
    !endif

    !if ( $needSpace == "false" )
        !if ( $whoStarts == 1 )
            !if ( $swap == "false" )
                $first $line> $second : include
            !endif
            !if ( $swap == "true" )
                $second <$line $first : include
            !endif
        !endif
        !if ( $whoStarts == 2 )
            !if ( $swap == "false" )
                $first <$line $second : include
            !endif
            !if ( $swap == "true" )
                $second $line> $first : include
            !endif
        !endif
    !endif
    !if ( $needSpace == "true" )
        !if ( $whoStarts == 1 )
            !if ( $swap == "false" )
                $first $line> $second : \t\t\tinclude
            !endif
            !if ( $swap == "true" )
                $second <$line $first : \t\t\tinclude
            !endif
        !endif
        !if ( $whoStarts == 2 )
            !if ( $swap == "false" )
                $first <$line $second : \t\t\tinclude
            !endif
            !if ( $swap == "true" )
                $second $line> $first : \t\t\tinclude
            !endif
        !endif
    !endif
!endfunction

' Fuctions for check valid characters in the relations
!function checkCharactersExceptSimpleLine($lineCheck)
    !if ( (%not(%strpos($lineCheck, ".") + "" == "-1")) || (%not(%strpos($lineCheck, ">") + "" == "-1")) || (%not(%strpos($lineCheck, "<") + "" == "-1")) || (%not(%strpos($lineCheck, "o") + "" == "-1")) || (%not(%strpos($lineCheck, "*") + "" == "-1")) || (%not(%strpos($lineCheck, "#") + "" == "-1")) || (%not(%strpos($lineCheck, "x") + "" == "-1")) || (%not(%strpos($lineCheck, "}") + "" == "-1")) || (%not(%strpos($lineCheck, "{") + "" == "-1")) || (%not(%strpos($lineCheck, "+") + "" == "-1")) || (%not(%strpos($lineCheck, "^") + "" == "-1")) || (%not(%strpos($lineCheck, "|") + "" == "-1")) )
        !return "true"
    !else
        !return "false"
!endfunction

!function checkCharactersExceptDot($lineCheck)
    !if ( (%not(%strpos($lineCheck, "-") + "" == "-1")) || (%not(%strpos($lineCheck, ">") + "" == "-1")) || (%not(%strpos($lineCheck, "<") + "" == "-1")) || (%not(%strpos($lineCheck, "o") + "" == "-1")) || (%not(%strpos($lineCheck, "*") + "" == "-1")) || (%not(%strpos($lineCheck, "#") + "" == "-1")) || (%not(%strpos($lineCheck, "x") + "" == "-1")) || (%not(%strpos($lineCheck, "}") + "" == "-1")) || (%not(%strpos($lineCheck, "{") + "" == "-1")) || (%not(%strpos($lineCheck, "+") + "" == "-1")) || (%not(%strpos($lineCheck, "^") + "" == "-1")) || (%not(%strpos($lineCheck, "|") + "" == "-1")) )
        !return "true"
    !else
        !return "false"
!endfunction

@enduml